server:
    port: 8000

eureka:
  client:
    healthcheck:
      enabled:  true 
      fetch-registry: true
      serviceUrl:
        defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

greeting: "그냥 서버!"
message: "Hello World! default!"


---

spring:
  profiles: dev 
    
greeting: "개발서버"
message: "Hello World! Dev!"

---

spring:
  profiles: stage
greeting: "스테이징서버"
message: "Hello World! Stage!"

---

spring:
  profiles: local
greeting: "로컬서버"
message: "Hello World! local!"
eureka:
  client:
        healthcheck:
          enabled:  true 
        fetch-registry: true
        serviceUrl:
            defaultZone: 
             ${vcap.services.eureka-service.credentials.uri:http://192.168.2.28:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
