server:
    port: 8763

eureka:
  client:
        healthcheck:
          enabled:  true 
        fetch-registry: true
        serviceUrl:
            defaultZone: 
             ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
greeting: "그냥 서버"
---

spring:
  profile: default
greeting: "디폴트 서버"

---

spring:
  profile: dev
greeting: "개발 서버"

---

spring:
  profile: stage
greeting: "스테이징 서버"

---

spring:
  profile: local
greeting: "로컬 서버"


