server:
    port: 8763

eureka:
  client:
        healthcheck:
          enabled:  true 
        fetch-registry: true
        serviceUrl:
            defaultZone: 
             ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  jpa: 
    hibernate:
      ddl-auto: update
      show_sql: true
      use_sql_comments: true
      fotmat_sql: true
  datasource:
    url: jdbc:mysql://mysql-test:3306/notice
    username: bosco74
    password: dkaghsms12!
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2
greeting: "그냥 서버"

---

spring:
  profiles: dev
greeting: "개발 서버"

---

spring:
  profiles: stage
greeting: "스테이징 서버"

---

spring:
  profiles: local

  datasource:
    url: jdbc:mysql://192.168.2.28:3306/notice
    username: bosco74
    password: dkaghsms12!
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2
greeting: "로컬 서버"
