server:
    port: 8763
eureka:
  client:
        healthcheck:
          enabled:  true 
        fetch-registry: true
        serviceUrl:
            defaultZone: 
             ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      use-sql-comments: true