server:
    port: 8763
eureka:
  client:
        healthcheck:
          enabled:  true 
        fetch-registry: true
        serviceUrl:
            defaultZone: 
             ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      use-sql-comments: true
  datasource:
    url: jdbc:mysql://mysql-test:3306/notice
    username: bosco74
    password: dkaghsms12!
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2
